### ISSUE TITLE
Will the tank parts open source?

### ISSUE THREAD

**Issue by anhtuannd** [GaryWong7/Farbung#1]
Hello,
This is the great project and I'm happy to open first issue :) 
I'm trying to build my own system but from the part list, the tank is yet to be available. Will it be open source?

**Comment by FilmNeverDie** [comment]
Yes it will be ! We are putting all the 3D models on soon! just organizing them now.  so good to hear you are building one, where are you building from?

**Comment by anhtuannd** [comment]
At the moment I just try to understand project structure. When the code is available, I will try to compile myself and may write unit test for it.

**Comment by FilmNeverDie** [comment]
The tank is now available in the 3D files if you got any question please let us know

**Comment by r-tae** [comment]
@anhtuannd I've just made a PR where I've added the source code to this repo (I'm not affiliated with FND, I just moved it from the SharePoint with their permission).

I have a pipe dream of setting up something like:
- Unit tests, probably using https://github.com/Arduino-CI/arduino_ci
- Doxygen (plus https://github.com/pieterdavid/mkdocs-doxygen-plugin) to generate documentation from source comments. This might be a bit of a boring job, but I think we just need to move the information from https://r-tae.github.io/Farbung/software/ into Javadoc-style comments

Just pinging you in case you were interested

**Comment by anhtuannd** [comment]
@r-tae 
I can help part of them. Doxygen I haven't used yet but it seems to be not far from Javadoc/Kdoc.

**Comment by r-tae** [comment]
Great! I've never actually used Doxygen either, so I'm not sure if its a good idea yet but at least Javadoc comments would be beneficial either way
